name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: test-flow

    steps:
    - uses: actions/checkout@master
    - name: Login to ACR by uid
      uses: denverdino/acr-login@master
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"
    - name: Build and push image to ACR
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/jingshan/nodejs-sample-app:$IMAGE_TAG .
        docker build -t registry.cn-hangzhou.aliyuncs.com/jingshan/nodejs-sample-app:$IMAGE_TAG registry.cn-hangzhou.aliyuncs.com/jingshan/nodejs-sample-app:latest
        docker push registry.cn-hangzhou.aliyuncs.com/jingshan/nodejs-sample-app